apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: n8n
  annotations:
    run.googleapis.com/cloudsql-instances: docmost-484110:europe-west1:docmost-2
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "0"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      serviceAccountName: 584964349468-compute@developer.gserviceaccount.com
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/docmost-484110/n8n:latest
        ports:
        - name: http1
          containerPort: 5678
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
        env:
        # App Configuration
        - name: N8N_PROTOCOL
          valueFrom:
            secretKeyRef:
              name: n8n-N8N_PROTOCOL
              key: latest
        - name: N8N_PORT
          valueFrom:
            secretKeyRef:
              name: n8n-N8N_PORT
              key: latest
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: n8n-NODE_ENV
              key: latest
        - name: N8N_METRICS
          valueFrom:
            secretKeyRef:
              name: n8n-N8N_METRICS
              key: latest
        - name: N8N_DIAGNOSTICS_ENABLED
          valueFrom:
            secretKeyRef:
              name: n8n-N8N_DIAGNOSTICS_ENABLED
              key: latest
        
        # Database Configuration
        - name: DB_TYPE
          valueFrom:
            secretKeyRef:
              name: n8n-DB_TYPE
              key: latest
        - name: DB_POSTGRESDB_HOST
          valueFrom:
            secretKeyRef:
              name: n8n-DB_POSTGRESDB_HOST
              key: latest
        - name: DB_POSTGRESDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: n8n-DB_POSTGRESDB_DATABASE
              key: latest
        - name: DB_POSTGRESDB_USER
          valueFrom:
            secretKeyRef:
              name: n8n-DB_POSTGRESDB_USER
              key: latest
        - name: DB_POSTGRESDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: n8n-DB_POSTGRESDB_PASSWORD
              key: latest
        - name: DB_POSTGRESDB_PORT
          valueFrom:
            secretKeyRef:
              name: n8n-DB_POSTGRESDB_PORT
              key: latest
        
        # Redis Configuration
        - name: QUEUE_BULL_REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: n8n-QUEUE_BULL_REDIS_HOST
              key: latest
        - name: QUEUE_BULL_REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: n8n-QUEUE_BULL_REDIS_PORT
              key: latest
        - name: QUEUE_BULL_REDIS_DB
          valueFrom:
            secretKeyRef:
              name: n8n-QUEUE_BULL_REDIS_DB
              key: latest
        - name: QUEUE_BULL_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: n8n-QUEUE_BULL_REDIS_PASSWORD
              key: latest
        - name: EXECUTIONS_MODE
          valueFrom:
            secretKeyRef:
              name: n8n-EXECUTIONS_MODE
              key: latest
        
        # Cloud Storage Configuration
        - name: N8N_DEFAULT_BINARY_DATA_MODE
          valueFrom:
            secretKeyRef:
              name: n8n-N8N_DEFAULT_BINARY_DATA_MODE
              key: latest
        - name: N8N_EXTERNAL_STORAGE_S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: n8n-N8N_EXTERNAL_STORAGE_S3_BUCKET_NAME
              key: latest
        - name: N8N_EXTERNAL_STORAGE_S3_BUCKET_REGION
          valueFrom:
            secretKeyRef:
              name: n8n-N8N_EXTERNAL_STORAGE_S3_BUCKET_REGION
              key: latest
        - name: N8N_EXTERNAL_STORAGE_S3_HOST
          valueFrom:
            secretKeyRef:
              name: n8n-N8N_EXTERNAL_STORAGE_S3_HOST
              key: latest
        - name: N8N_EXTERNAL_STORAGE_S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: n8n-N8N_EXTERNAL_STORAGE_S3_ACCESS_KEY
              key: latest
        - name: N8N_EXTERNAL_STORAGE_S3_ACCESS_SECRET
          valueFrom:
            secretKeyRef:
              name: n8n-N8N_EXTERNAL_STORAGE_S3_ACCESS_SECRET
              key: latest
        
        # Security Configuration
        - name: N8N_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: n8n-N8N_ENCRYPTION_KEY
              key: latest
        
        startupProbe:
          httpGet:
            path: /healthz
            port: 5678
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5678
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz/readiness
            port: 5678
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 3
